import { Injectable } from '@angular/core';
import { Bodies } from './bodies';

@Injectable({
  providedIn: 'root'
})
export class BodiesService {

  bodiesList: Bodies[] = [
    { 
      id: 3000,
      name: '',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
      { 
      id: -1,
      name: '=Fending=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 3001,
      name: 'Ascension Mail of Fending',
      slot: 'Body',
      strength: 394,
      dexterity: 0,
      vitality: 440,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 204,
      directhit: 0,
      defense: 1196,
      magicdefense: 1196,
      tenacity: 292,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/c/cb/Ascension_Mail_of_Fending_Icon.png'
      },
      { 
      id: 3002,
      name: 'Augmented Credendum Cuirass of Fending',
      slot: 'Body',
      strength: 394,
      dexterity: 0,
      vitality: 440,
      intelligence: 0,
      mind: 0,
      criticalhit: 292,
      determination: 204,
      directhit: 0,
      defense: 1196,
      magicdefense: 1196,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/a/a2/Augmented_Credendum_Cuirass_of_Fending_Icon.png'
      },
      { 
      id: -1,
      name: '=Healing=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 3003,
      name: 'Ascension Robe of Healing',
      slot: 'Body',
      strength: 0,
      dexterity: 0,
      vitality: 396,
      intelligence: 0,
      mind: 394,
      criticalhit: 292,
      determination: 204,
      directhit: 0,
      defense: 478,
      magicdefense: 837,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/a/aa/Ascension_Robe_of_Healing_Icon.png'
      },
      { 
      id: 3004,
      name: 'Augmented Credendum Surcoat of Healing',
      slot: 'Body',
      strength: 0,
      dexterity: 0,
      vitality: 396,
      intelligence: 0,
      mind: 394,
      criticalhit: 0,
      determination: 204,
      directhit: 0,
      defense: 478,
      magicdefense: 837,
      tenacity: 0,
      piety: 292,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/4/46/Augmented_Credendum_Surcoat_of_Healing_Icon.png'
      },
      { 
        id: -1,
        name: '=Striking=',
        slot: '',
        strength: 0,
        dexterity: 0,
        vitality: 0,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 0,
        directhit: 0,
        defense: 0,
        magicdefense: 0,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: ''
        },
      { 
        id: 3005,
        name: 'Ascension Cloak of Striking',
        slot: 'Body',
        strength: 394,
        dexterity: 0,
        vitality: 440,
        intelligence: 0,
        mind: 0,
        criticalhit: 204,
        determination: 0,
        directhit: 292,
        defense: 658,
        magicdefense: 658,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/f/f0/Ascension_Cloak_of_Striking_Icon.png'
        },
        { 
        id: 3006,
        name: 'Augmented Credendum Corselet of Striking',
        slot: 'Body',
        strength: 394,
        dexterity: 0,
        vitality: 440,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 292,
        directhit: 204,
        defense: 658,
        magicdefense: 658,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/1/14/Augmented_Credendum_Corselet_of_Striking_Icon.png'
      },
      { 
        id: -1,
        name: '=Maiming=',
        slot: '',
        strength: 0,
        dexterity: 0,
        vitality: 0,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 0,
        directhit: 0,
        defense: 0,
        magicdefense: 0,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: ''
        },
      { 
        id: 3007,
        name: 'Ascension Mail of Maiming',
        slot: 'Body',
        strength: 394,
        dexterity: 0,
        vitality: 440,
        intelligence: 0,
        mind: 0,
        criticalhit: 292,
        determination: 204,
        directhit: 0,
        defense: 837,
        magicdefense: 658,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/9/90/Ascension_Mail_of_Maiming_Icon.png'
        },
        { 
        id: 3008,
        name: 'Augmented Credendum Cuirass of Maiming ',
        slot: 'Body',
        strength: 394,
        dexterity: 0,
        vitality: 440,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 292,
        directhit: 204,
        defense: 837,
        magicdefense: 658,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/2/23/Augmented_Credendum_Cuirass_of_Maiming_Icon.png'
      },
      { 
    id: -1,
    name: '=Scouting=',
    slot: '',
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
  { 
    id: 3009,
    name: 'Ascension Cloak of Scouting',
    slot: 'Body',
    strength: 0,
    dexterity: 394,
    vitality: 440,
    intelligence: 0,
    mind: 0,
    criticalhit: 292,
    determination: 204,
    directhit: 0,
    defense: 658,
    magicdefense: 658,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/4/44/Ascension_Cloak_of_Scouting_Icon.png'
  },      
  { 
    id: 3010,
    name: 'Augmented Credendum Corselet of Scouting',
    slot: 'Body',
    strength: 0,
    dexterity: 394,
    vitality: 440,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 204,
    directhit: 292,
    defense: 658,
    magicdefense: 658,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/c/c4/Augmented_Credendum_Corselet_of_Scouting_Icon.png'
    },
        { 
      id: -1,
      name: '=Aiming=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 3011,
      name: 'Ascension Cloak of Aiming',
      slot: 'Body',
      strength: 0,
      dexterity: 394,
      vitality: 440,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 204,
      directhit: 292,
      defense: 658,
      magicdefense: 658,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/2/23/Ascension_Cloak_of_Aiming_Icon.png'
    },      
    { 
      id: 3012,
      name: 'Augmented Credendum Mail of Aiming ',
      slot: 'Body',
      strength: 0,
      dexterity: 394,
      vitality: 440,
      intelligence: 0,
      mind: 0,
      criticalhit: 204,
      determination: 292,
      directhit: 0,
      defense: 658,
      magicdefense: 658,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/c/c3/Augmented_Credendum_Mail_of_Aiming_Icon.png'
      },
      { 
      id: -1,
      name: '=Casting=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 2013,
      name: 'Ascension Robe of Casting',
      slot: 'Body',
      strength: 0,
      dexterity: 0,
      vitality: 396,
      intelligence: 394,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 204,
      defense: 357,
      magicdefense: 624,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 292,
      photo: 'https://ffxiv.gamerescape.com/w/images/b/b0/Ascension_Robe_of_Casting_Icon.png'
      },      
      { 
      id: 2014,
      name: 'Augmented Credendum Surcoat of Casting',
      slot: 'Body',
      strength: 0,
      dexterity: 0,
      vitality: 396,
      intelligence: 394,
      mind: 0,
      criticalhit: 292,
      determination: 204,
      directhit: 0,
      defense: 478,
      magicdefense: 837,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/5/50/Augmented_Credendum_Surcoat_of_Casting_Icon.png'
      },
  ]

    getBodies() : Bodies[] {
      return this.bodiesList
    }
}
