import { Injectable } from '@angular/core';
import { Bodies } from './bodies';

@Injectable({
  providedIn: 'root'
})
export class BodiesService {

  bodiesList: Bodies[] = [
    { 
      id: 3000,
      name: '',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
      { 
        id: -2,
        name: '===Tank===',
        slot: '',
        strength: 0,
        dexterity: 0,
        vitality: 0,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 0,
        directhit: 0,
        defense: 0,
        magicdefense: 0,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: ''
        },
      { 
        id: 3001,
        name: 'Ascension Mail of Fending',
        slot: 'Body',
        strength: 394,
        dexterity: 0,
        vitality: 440,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 204,
        directhit: 0,
        defense: 1196,
        magicdefense: 1196,
        tenacity: 292,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/c/cb/Ascension_Mail_of_Fending_Icon.png'
        },
        { 
          id: 3002,
          name: 'Augmented Credendum Cuirass of Fending',
          slot: 'Body',
          strength: 394,
          dexterity: 0,
          vitality: 440,
          intelligence: 0,
          mind: 0,
          criticalhit: 292,
          determination: 204,
          directhit: 0,
          defense: 1196,
          magicdefense: 1196,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 0,
          photo: 'https://ffxiv.gamerescape.com/w/images/a/a2/Augmented_Credendum_Cuirass_of_Fending_Icon.png'
          },
          { 
            id: 3003,
            name: 'Credendum Cuirass of Fending',
            slot: 'Body',
            strength: 374,
            dexterity: 0,
            vitality: 413,
            intelligence: 0,
            mind: 0,
            criticalhit: 286,
            determination: 200,
            directhit: 0,
            defense: 1171,
            magicdefense: 1171,
            tenacity: 0,
            piety: 0,
            skillspeed: 0,
            spellspeed: 0,
            photo: 'https://ffxiv.gamerescape.com/w/images/8/83/Credendum_Cuirass_of_Fending_Icon.png'
            },
            { 
              id: 3004,
              name: 'Augmented Diadochos Jacket of Fending',
              slot: 'Body',
              strength: 374,
              dexterity: 0,
              vitality: 413,
              intelligence: 0,
              mind: 0,
              criticalhit: 200,
              determination: 286,
              directhit: 0,
              defense: 1171,
              magicdefense: 1171,
              tenacity: 0,
              piety: 0,
              skillspeed: 0,
              spellspeed: 0,
              photo: 'https://ffxiv.gamerescape.com/w/images/7/71/Augmented_Diadochos_Jacket_of_Fending_Icon.png'
              },
              { 
                id: -2,
                name: '===Healer===',
                slot: 'Please choose a different',
                strength: 0,
                dexterity: 0,
                vitality: 0,
                intelligence: 0,
                mind: 0,
                criticalhit: 0,
                determination: 0,
                directhit: 0,
                defense: 0,
                magicdefense: 0,
                tenacity: 0,
                piety: 0,
                skillspeed: 0,
                spellspeed: 0,
                photo: ''
                },
      { 
        id: 3060,
        name: 'Augmented Diadochos Coat of Healing ',
        slot: 'Body',
        strength: 0,
        dexterity: 0,
        vitality: 372,
        intelligence: 0,
        mind: 374,
        criticalhit: 200,
        determination: 286,
        directhit: 0,
        defense: 468,
        magicdefense: 820,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/2/2e/Augmented_Diadochos_Coat_of_Healing_Icon.png'
        },
  ]

    getBodies() : Bodies[] {
      return this.bodiesList
    }
}
