import { Injectable } from '@angular/core';
import { Bracelets } from './bracelets';

@Injectable({
  providedIn: 'root'
})
export class BraceletsService {
  braceletsList: Bracelets[] = [
    { 
      id: -1,
      name: '',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
      { 
      id: -1,
      name: '=Fending=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 9001,
      name: 'Ascension Bracelet of Fending',
      slot: 'Bracelet',
      strength: 196,
      dexterity: 0,
      vitality: 218,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 145,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 102,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/d/dd/Ascension_Bracelet_of_Fending_Icon.png'
      },
      { 
      id: 9002,
      name: 'Augmented Credendum Bracelets of Fending',
      slot: 'Bracelet',
      strength: 196,
      dexterity: 0,
      vitality: 218,
      intelligence: 0,
      mind: 0,
      criticalhit: 145,
      determination: 102,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/4/4c/Augmented_Credendum_Bracelets_of_Fending_Icon.png'
      },
      { 
      id: -1,
      name: '=Healing=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 9003,
      name: 'Ascension Bracelet of Healing',
      slot: 'Bracelet',
      strength: 0,
      dexterity: 0,
      vitality: 196,
      intelligence: 0,
      mind: 196,
      criticalhit: 145,
      determination: 102,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/d/dd/Ascension_Bracelet_of_Fending_Icon.png'
      },
      { 
      id: 9004,
      name: 'Augmented Credendum Bracelets of Healing',
      slot: 'Bracelet',
      strength: 0,
      dexterity: 0,
      vitality: 196,
      intelligence: 0,
      mind: 196,
      criticalhit: 0,
      determination: 145,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 102,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/4/4c/Augmented_Credendum_Bracelets_of_Fending_Icon.png'
      },
      { 
        id: -1,
        name: '=Maiming, Striking=',
        slot: '',
        strength: 0,
        dexterity: 0,
        vitality: 0,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 0,
        directhit: 0,
        defense: 0,
        magicdefense: 0,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: ''
        },
      { 
        id: 9005,
        name: 'Ascension Bracelet of Slaying',
        slot: 'Bracelet',
        strength: 196,
        dexterity: 0,
        vitality: 218,
        intelligence: 0,
        mind: 0,
        criticalhit: 145,
        determination: 0,
        directhit: 102,
        defense: 1,
        magicdefense: 1,
        tenacity: 0,
        piety: 0,
        skillspeed: 102,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/d/dd/Ascension_Bracelet_of_Fending_Icon.png'
        },
        { 
        id: 9006,
        name: 'Augmented Credendum Bracelets of Slaying',
        slot: 'Bracelet',
        strength: 196,
        dexterity: 0,
        vitality: 218,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 102,
        directhit: 145,
        defense: 1,
        magicdefense: 1,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/4/4c/Augmented_Credendum_Bracelets_of_Fending_Icon.png'
        },
        { 
      id: -1,
      name: '=Aiming, Scouting=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 9007,
      name: 'Ascension Bracelet of Aiming',
      slot: 'Bracelet',
      strength: 0,
      dexterity: 196,
      vitality: 218,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 145,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 102,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/d/dd/Ascension_Bracelet_of_Fending_Icon.png'
      },
      { 
      id: 9008,
      name: 'Augmented Credendum Bracelets of Aiming',
      slot: 'Bracelet',
      strength: 0,
      dexterity: 196,
      vitality: 218,
      intelligence: 0,
      mind: 0,
      criticalhit: 102,
      determination: 145,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/4/4c/Augmented_Credendum_Bracelets_of_Fending_Icon.png'
      },
      { 
      id: -1,
      name: '=Casting=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 9009,
      name: 'Ascension Bracelet of Casting',
      slot: 'Bracelet',
      strength: 0,
      dexterity: 0,
      vitality: 196,
      intelligence: 196,
      mind: 0,
      criticalhit: 145,
      determination: 102,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 102,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/d/dd/Ascension_Bracelet_of_Fending_Icon.png'
      },
      { 
      id: 9010,
      name: 'Augmented Credendum Bracelets of Fending',
      slot: 'Bracelet',
      strength: 0,
      dexterity: 0,
      vitality: 196,
      intelligence: 196,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 145,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 102,
      photo: 'https://ffxiv.gamerescape.com/w/images/4/4c/Augmented_Credendum_Bracelets_of_Fending_Icon.png'
      },
  ]

    getBracelets() : Bracelets[] {
      return this.braceletsList
    }
  
}
