import { Injectable } from '@angular/core';
import { Earrings } from './earrings';

@Injectable({
  providedIn: 'root'
})
export class EarringsService {

  earringsList: Earrings[] = [
    { 
      id: -1,
      name: '',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
      { 
      id: -1,
      name: '=Fending=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 7001,
      name: 'Ascension Earring of Fending',
      slot: 'Earring',
      strength: 196,
      dexterity: 0,
      vitality: 218,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 145,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 102,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/7/7f/Ascension_Earring_of_Fending_Icon.png'
      },
      { 
      id: 7002,
      name: 'Augmented Credendum Earring of Fending',
      slot: 'Earring',
      strength: 196,
      dexterity: 0,
      vitality: 218,
      intelligence: 0,
      mind: 0,
      criticalhit: 145,
      determination: 102,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/5/55/Augmented_Credendum_Earrings_of_Fending_Icon.png'
      },
      { 
      id: 7011,
      name: 'Augmented Diadochos Earring of Fending',
      slot: 'Earring',
      strength: 186,
      dexterity: 0,
      vitality: 205,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 99,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 142,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/c/c1/Augmented_Diadochos_Earring_of_Fending_Icon.png'
      },
      { 
      id: -1,
      name: '=Healing=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 7003,
      name: 'Ascension Earring of Healing',
      slot: 'Earring',
      strength: 0,
      dexterity: 0,
      vitality: 196,
      intelligence: 0,
      mind: 196,
      criticalhit: 145,
      determination: 0,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 102,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/7/7f/Ascension_Earring_of_Fending_Icon.png'
      },
      { 
      id: 7004,
      name: 'Augmented Credendum Earring of Healing',
      slot: 'Earring',
      strength: 0,
      dexterity: 0,
      vitality: 196,
      intelligence: 0,
      mind: 196,
      criticalhit: 0,
      determination: 145,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 102,
      photo: 'https://ffxiv.gamerescape.com/w/images/5/55/Augmented_Credendum_Earrings_of_Fending_Icon.png'
      },
      { 
      id: 7012,
      name: 'Augmented Diadochos Earring of Healing',
      slot: 'Earring',
      strength: 0,
      dexterity: 0,
      vitality: 185,
      intelligence: 0,
      mind: 186,
      criticalhit: 0,
      determination: 142,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 99,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/c/c1/Augmented_Diadochos_Earring_of_Fending_Icon.png'
      },
      { 
        id: -1,
        name: '=Maiming, Striking=',
        slot: '',
        strength: 0,
        dexterity: 0,
        vitality: 0,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 0,
        directhit: 0,
        defense: 0,
        magicdefense: 0,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: ''
        },
      { 
        id: 7005,
        name: 'Ascension Earring of Slaying',
        slot: 'Earring',
        strength: 196,
        dexterity: 0,
        vitality: 218,
        intelligence: 0,
        mind: 0,
        criticalhit: 145,
        determination: 102,
        directhit: 0,
        defense: 1,
        magicdefense: 1,
        tenacity: 0,
        piety: 0,
        skillspeed: 145,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/7/7f/Ascension_Earring_of_Fending_Icon.png'
        },
        { 
        id: 7006,
        name: 'Augmented Credendum Earring of Slaying',
        slot: 'Earring',
        strength: 196,
        dexterity: 0,
        vitality: 218,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 102,
        directhit: 0,
        defense: 1,
        magicdefense: 1,
        tenacity: 0,
        piety: 0,
        skillspeed: 145,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/5/55/Augmented_Credendum_Earrings_of_Fending_Icon.png'
      },
      { 
      id: 7013,
      name: 'Augmented Diadochos Earring of Slaying',
      slot: 'Earring',
      strength: 186,
      dexterity: 0,
      vitality: 205,
      intelligence: 0,
      mind: 0,
      criticalhit: 99,
      determination: 0,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 142,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/c/c1/Augmented_Diadochos_Earring_of_Fending_Icon.png'
      },
        { 
      id: -1,
      name: '=Aiming, Scouting=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 7007,
      name: 'Ascension Earring of Aiming',
      slot: 'Earring',
      strength: 0,
      dexterity: 196,
      vitality: 218,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 102,
      directhit: 145,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/7/7f/Ascension_Earring_of_Fending_Icon.png'
    },      
    { 
      id: 7008,
      name: 'Augmented Credendum Earring of Aiming',
      slot: 'Earring',
      strength: 0,
      dexterity: 196,
      vitality: 218,
      intelligence: 0,
      mind: 0,
      criticalhit: 102,
      determination: 145,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/5/55/Augmented_Credendum_Earrings_of_Fending_Icon.png'
      },
      { 
      id: 7014,
      name: 'Augmented Diadochos Earring of Aiming',
      slot: 'Earring',
      strength: 0,
      dexterity: 186,
      vitality: 205,
      intelligence: 0,
      mind: 0,
      criticalhit: 142,
      determination: 0,
      directhit: 99,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/c/c1/Augmented_Diadochos_Earring_of_Fending_Icon.png'
      },
      { 
      id: -1,
      name: '=Casting=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 7009,
      name: 'Ascension Earring of Casting',
      slot: 'Earring',
      strength: 0,
      dexterity: 0,
      vitality: 196,
      intelligence: 196,
      mind: 0,
      criticalhit: 145,
      determination: 102,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/7/7f/Ascension_Earring_of_Fending_Icon.png'
      },      
      { 
      id: 7010,
      name: 'Augmented Credendum Earring of Casting',
      slot: 'Earring',
      strength: 0,
      dexterity: 0,
      vitality: 196,
      intelligence: 196,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 102,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 145,
      photo: 'https://ffxiv.gamerescape.com/w/images/5/55/Augmented_Credendum_Earrings_of_Fending_Icon.png'
      },
      { 
      id: 7015,
      name: 'Augmented Diadochos Earring of Casting',
      slot: 'Earring',
      strength: 0,
      dexterity: 0,
      vitality: 185,
      intelligence: 186,
      mind: 0,
      criticalhit: 0,
      determination: 142,
      directhit: 99,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/c/c1/Augmented_Diadochos_Earring_of_Fending_Icon.png'
      },
  ]

  getEarrings() : Earrings[] {
    return this.earringsList
  }
}
