import { Injectable } from '@angular/core';
import { Feet } from './feet';

@Injectable({
  providedIn: 'root'
})
export class FeetService {

  feetList: Feet[] = [
    { 
      id: -1,
      name: '',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
      { 
      id: -1,
      name: '=Fending=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 6001,
      name: 'Ascension Sollerets of Fending',
      slot: 'Feet',
      strength: 248,
      dexterity: 0,
      vitality: 277,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 129,
      directhit: 0,
      defense: 892,
      magicdefense: 892,
      tenacity: 0,
      piety: 0,
      skillspeed: 184,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/f/fb/Ascension_Sollerets_of_Fending_Icon.png'
      },
      { 
      id: 6002,
      name: 'Augmented Credendum Sollerets of Fending',
      slot: 'Feet',
      strength: 248,
      dexterity: 0,
      vitality: 277,
      intelligence: 0,
      mind: 0,
      criticalhit: 184,
      determination: 129,
      directhit: 0,
      defense: 892,
      magicdefense: 892,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/0/05/Augmented_Credendum_Sollerets_of_Fending_Icon.png'
      },
      { 
      id: 6015,
      name: 'Augmented Diadochos Boots of Fending',
      slot: 'Feet',
      strength: 235,
      dexterity: 0,
      vitality: 260,
      intelligence: 0,
      mind: 0,
      criticalhit: 126,
      determination: 0,
      directhit: 0,
      defense: 873,
      magicdefense: 873,
      tenacity: 0,
      piety: 0,
      skillspeed: 180,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/4/4e/Augmented_Diadochos_Boots_of_Fending_Icon.png'
      },
      { 
      id: -1,
      name: '=Healing=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 6003,
      name: 'Ascension Sandals of Healing',
      slot: 'Feet',
      strength: 0,
      dexterity: 0,
      vitality: 249,
      intelligence: 0,
      mind: 248,
      criticalhit: 184,
      determination: 129,
      directhit: 0,
      defense: 357,
      magicdefense: 624,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/3/36/Ascension_Sandals_of_Healing_Icon.png'
      },
      { 
      id: 6004,
      name: 'Augmented Credendum Earring of Healing',
      slot: 'Feet',
      strength: 0,
      dexterity: 0,
      vitality: 249,
      intelligence: 0,
      mind: 248,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 357,
      magicdefense: 624,
      tenacity: 0,
      piety: 129,
      skillspeed: 0,
      spellspeed: 184,
      photo: 'https://ffxiv.gamerescape.com/w/images/a/a0/Augmented_Credendum_Sollerets_of_Healing_Icon.png'
      },
      { 
      id: 6016,
      name: 'Augmented Diadochos Boots of Healing',
      slot: 'Feet',
      strength: 0,
      dexterity: 0,
      vitality: 234,
      intelligence: 0,
      mind: 235,
      criticalhit: 126,
      determination: 0,
      directhit: 0,
      defense: 349,
      magicdefense: 611,
      tenacity: 0,
      piety: 180,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/d/d7/Augmented_Diadochos_Boots_of_Healing_Icon.png'
      },
      { 
        id: -1,
        name: '=Striking=',
        slot: '',
        strength: 0,
        dexterity: 0,
        vitality: 0,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 0,
        directhit: 0,
        defense: 0,
        magicdefense: 0,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: ''
        },
      { 
        id: 6005,
        name: 'Ascension Sabatons of Striking',
        slot: 'Feet',
        strength: 248,
        dexterity: 0,
        vitality: 277,
        intelligence: 0,
        mind: 0,
        criticalhit: 184,
        determination: 129,
        directhit: 0,
        defense: 491,
        magicdefense: 491,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/1/18/Ascension_Sabatons_of_Striking_Icon.png'
        },
        { 
        id: 6006,
        name: 'Augmented Credendum Longboots of Striking',
        slot: 'Feet',
        strength: 248,
        dexterity: 0,
        vitality: 277,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 0,
        directhit: 184,
        defense: 491,
        magicdefense: 491,
        tenacity: 0,
        piety: 0,
        skillspeed: 129,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/9/9b/Augmented_Credendum_Longboots_of_Striking_Icon.png'
      },
      { 
      id: 6017,
      name: 'Augmented Diadochos Shoes of Striking',
      slot: 'Feet',
      strength: 235,
      dexterity: 0,
      vitality: 260,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 180,
      directhit: 126,
      defense: 480,
      magicdefense: 480,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/6/69/Augmented_Diadochos_Shoes_of_Striking_Icon.png'
    },
      { 
        id: -1,
        name: '=Maiming=',
        slot: '',
        strength: 0,
        dexterity: 0,
        vitality: 0,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 0,
        directhit: 0,
        defense: 0,
        magicdefense: 0,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: ''
        },
      { 
        id: 6007,
        name: 'Ascension Sollerets of Maiming ',
        slot: 'Feet',
        strength: 248,
        dexterity: 0,
        vitality: 277,
        intelligence: 0,
        mind: 0,
        criticalhit: 184,
        determination: 0,
        directhit: 129,
        defense: 624,
        magicdefense: 491,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/4/43/Ascension_Sollerets_of_Maiming_Icon.png'
        },
        { 
        id: 6008,
        name: 'Augmented Credendum Sollerets of Maiming ',
        slot: 'Feet',
        strength: 248,
        dexterity: 0,
        vitality: 277,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 0,
        directhit: 129,
        defense: 624,
        magicdefense: 491,
        tenacity: 0,
        piety: 0,
        skillspeed: 184,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/5/51/Augmented_Credendum_Sollerets_of_Maiming_Icon.png'
      },
      { 
      id: 6018,
      name: 'Augmented Diadochos Boots of Maiming',
      slot: 'Feet',
      strength: 235,
      dexterity: 0,
      vitality: 260,
      intelligence: 0,
      mind: 0,
      criticalhit: 180,
      determination: 126,
      directhit: 0,
      defense: 611,
      magicdefense: 480,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/6/6f/Augmented_Diadochos_Boots_of_Maiming_Icon.png'
    },
      { 
    id: -1,
    name: '=Scouting=',
    slot: '',
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
  { 
    id: 6009,
    name: 'Ascension Sabatons of Scouting',
    slot: 'Feet',
    strength: 0,
    dexterity: 248,
    vitality: 277,
    intelligence: 0,
    mind: 0,
    criticalhit: 129,
    determination: 0,
    directhit: 184,
    defense: 491,
    magicdefense: 491,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/3/3a/Ascension_Sabatons_of_Scouting_Icon.png'
  },      
  { 
    id: 6010,
    name: 'Augmented Credendum Shoes of Scouting',
    slot: 'Feet',
    strength: 0,
    dexterity: 248,
    vitality: 277,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 184,
    directhit: 0,
    defense: 491,
    magicdefense: 491,
    tenacity: 0,
    piety: 0,
    skillspeed: 129,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/9/94/Augmented_Credendum_Longboots_of_Scouting_Icon.png'
    },      
  { 
    id: 6019,
    name: 'Augmented Diadochos Shoes of Scouting',
    slot: 'Feet',
    strength: 0,
    dexterity: 235,
    vitality: 260,
    intelligence: 0,
    mind: 0,
    criticalhit: 180,
    determination: 126,
    directhit: 0,
    defense: 491,
    magicdefense: 491,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/c/c0/Augmented_Diadochos_Shoes_of_Scouting_Icon.png'
    },
        { 
      id: -1,
      name: '=Aiming=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 6011,
      name: 'Ascension Sabatons of Aiming',
      slot: 'Earring',
      strength: 0,
      dexterity: 248,
      vitality: 277,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 129,
      defense: 491,
      magicdefense: 491,
      tenacity: 0,
      piety: 0,
      skillspeed: 184,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/5/5d/Ascension_Sabatons_of_Aiming_Icon.png'
    },      
    { 
      id: 6012,
      name: 'Augmented Credendum Shoes of Aiming',
      slot: 'Feet',
      strength: 0,
      dexterity: 248,
      vitality: 277,
      intelligence: 0,
      mind: 0,
      criticalhit: 129,
      determination: 0,
      directhit: 184,
      defense: 491,
      magicdefense: 491,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/d/d4/Augmented_Credendum_Shoes_of_Aiming_Icon.png'
      },      
    { 
      id: 6020,
      name: 'Augmented Diadochos Boots of Aiming',
      slot: 'Feet',
      strength: 0,
      dexterity: 235,
      vitality: 260,
      intelligence: 0,
      mind: 0,
      criticalhit: 126,
      determination: 0,
      directhit: 0,
      defense: 480,
      magicdefense: 480,
      tenacity: 0,
      piety: 0,
      skillspeed: 180,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/9/96/Augmented_Diadochos_Boots_of_Aiming_Icon.png'
      },
      { 
      id: -1,
      name: '=Casting=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 6013,
      name: 'Ascension Sandals of Casting',
      slot: 'Feet',
      strength: 0,
      dexterity: 0,
      vitality: 249,
      intelligence: 248,
      mind: 0,
      criticalhit: 0,
      determination: 184,
      directhit: 0,
      defense: 357,
      magicdefense: 624,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 129,
      photo: 'https://ffxiv.gamerescape.com/w/images/0/0f/Ascension_Sandals_of_Casting_Icon.png'
      },      
      { 
      id: 6014,
      name: 'Augmented Credendum Sollerets of Casting',
      slot: 'Feet',
      strength: 0,
      dexterity: 0,
      vitality: 249,
      intelligence: 248,
      mind: 0,
      criticalhit: 129,
      determination: 0,
      directhit: 184,
      defense: 357,
      magicdefense: 624,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/9/90/Augmented_Credendum_Sollerets_of_Casting_Icon.png'
      },      
      { 
      id: 6021,
      name: 'Augmented Diadochos Boots of Casting',
      slot: 'Feet',
      strength: 0,
      dexterity: 0,
      vitality: 234,
      intelligence: 235,
      mind: 0,
      criticalhit: 180,
      determination: 0,
      directhit: 0,
      defense: 349,
      magicdefense: 611,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 126,
      photo: 'https://ffxiv.gamerescape.com/w/images/7/7c/Augmented_Diadochos_Boots_of_Casting_Icon.png'
      },
  ]

  getFeet() : Feet[] {
    return this.feetList
  }
}
