import { Injectable } from '@angular/core';
import { Items } from './items';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';

@Injectable({
  providedIn: 'root'
})

export class ItemsService {

  itemsList: Items[] = [
    {
      id: -1,
    name: '',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: -1,
    name: '=Paladin=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1000,
    name: 'Mandervillous Falchion + Mandervillous Kite Shield',
    slot: 'Weapon',
    damage: 132,
    strength: 416,
    dexterity: 0,
    vitality: 458,
    intelligence: 0,
    mind: 0,
    criticalhit: 306,
    determination: 306,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 72,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/c/ce/Mandervillous_Falchion_Icon.png'
    },
    {
      id: 1001,
    name: 'Augmented Polaris Point + Augmented Vessel',
    slot: 'Weapon',
    damage: 131,
    strength: 409,
    dexterity: 0,
    vitality: 456,
    intelligence: 0,
    mind: 0,
    criticalhit: 303,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 212,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/5/53/Augmented_Polaris_Point_Icon.png'
    },
    {
      id: -1,
    name: '=Warrior=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1002,
    name: 'Mandervillous Battleaxe',
    slot: 'Weapon',
    damage: 132,
    strength: 416,
    dexterity: 0,
    vitality: 458,
    intelligence: 0,
    mind: 0,
    criticalhit: 306,
    determination: 306,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 72,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/6/6f/Mandervillous_Battleaxe_Icon.png'
    },
    {
      id: 1003,
    name: 'Augmented Wrathgrinder',
    slot: 'Weapon',
    damage: 131,
    strength: 409,
    dexterity: 0,
    vitality: 456,
    intelligence: 0,
    mind: 0,
    criticalhit: 303,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 212,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/5/58/Augmented_Wrathgrinder_Icon.png'
    },
    
    {
      id: -1,
    name: '=Dark Knight=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1004,
    name: 'Mandervillous Greatsword',
    slot: 'Weapon',
    damage: 132,
    strength: 416,
    dexterity: 0,
    vitality: 458,
    intelligence: 0,
    mind: 0,
    criticalhit: 306,
    determination: 306,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 72,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/b/bc/Mandervillous_Greatsword_Icon.png'
    },
    {
      id: 1005,
    name: 'Augmented Blood Rapture',
    slot: 'Weapon',
    damage: 131,
    strength: 409,
    dexterity: 0,
    vitality: 456,
    intelligence: 0,
    mind: 0,
    criticalhit: 303,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 212,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/7/71/Augmented_Blood_Rapture_Icon.png'
    },
    {
      id: -1,
    name: '=Gunbreaker=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1006,
    name: 'Mandervillous Gunblade',
    slot: 'Weapon',
    damage: 132,
    strength: 416,
    dexterity: 0,
    vitality: 458,
    intelligence: 0,
    mind: 0,
    criticalhit: 306,
    determination: 306,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 72,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/3/3b/Mandervillous_Gunblade_Icon.png'
    },
    {
      id: 1007,
    name: 'Augmented Cerberus Fang',
    slot: 'Weapon',
    damage: 131,
    strength: 409,
    dexterity: 0,
    vitality: 456,
    intelligence: 0,
    mind: 0,
    criticalhit: 303,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 212,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/d/d2/Augmented_Cerberus_Fang_Icon.png'
    },
    {
      id: -1,
    name: '=White Mage=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1008,
    name: 'Mandervillous Cane',
    slot: 'Weapon',
    damage: 132,
    strength: 0,
    dexterity: 0,
    vitality: 412,
    intelligence: 0,
    mind: 416,
    criticalhit: 306,
    determination: 306,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 72,
    photo: 'https://ffxiv.gamerescape.com/w/images/6/6d/Mandervillous_Cane_Icon.png'
    },
    {
      id: 1009,
    name: 'Augmented Bunnys Crescent',
    slot: 'Weapon',
    damage: 131,
    strength: 0,
    dexterity: 0,
    vitality: 410,
    intelligence: 0,
    mind: 409,
    criticalhit: 212,
    determination: 303,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/f/ff/Augmented_Bunny%27s_Crescent_Icon.png'
    },
    {
      id: -1,
    name: '=Scholar=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1010,
    name: 'Mandervillous Codex',
    slot: 'Weapon',
    damage: 132,
    strength: 0,
    dexterity: 0,
    vitality: 412,
    intelligence: 0,
    mind: 416,
    criticalhit: 306,
    determination: 306,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 72,
    photo: 'https://ffxiv.gamerescape.com/w/images/d/d4/Mandervillous_Codex_Icon.png'
    },
    {
      id: 1011,
    name: 'Augmented Faerie Fancy',
    slot: 'Weapon',
    damage: 131,
    strength: 0,
    dexterity: 0,
    vitality: 410,
    intelligence: 0,
    mind: 409,
    criticalhit: 212,
    determination: 303,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/4/44/Augmented_Faerie_Fancy_Icon.png'
    },
    
    {
      id: -1,
    name: '=Astrologian=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1012,
    name: 'Mandervillous Torquetum',
    slot: 'Weapon',
    damage: 132,
    strength: 0,
    dexterity: 0,
    vitality: 412,
    intelligence: 0,
    mind: 416,
    criticalhit: 306,
    determination: 306,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 72,
    photo: 'https://ffxiv.gamerescape.com/w/images/a/a5/Mandervillous_Torquetum_Icon.png'
    },
    {
      id: 1013,
    name: 'Augmented Star Gazer',
    slot: 'Weapon',
    damage: 131,
    strength: 0,
    dexterity: 0,
    vitality: 410,
    intelligence: 0,
    mind: 409,
    criticalhit: 212,
    determination: 303,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/9/91/Augmented_Star_Gazer_Icon.png'
    },
    {
      id: -1,
    name: '=Sage=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1014,
    name: 'Mandervillous Wings',
    slot: 'Weapon',
    damage: 132,
    strength: 0,
    dexterity: 0,
    vitality: 412,
    intelligence: 0,
    mind: 416,
    criticalhit: 306,
    determination: 306,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 72,
    photo: 'https://ffxiv.gamerescape.com/w/images/c/c1/Mandervillous_Wings_Icon.png'
    },
    {
      id: 1015,
    name: 'Augmented Isnae Phis',
    slot: 'Weapon',
    damage: 131,
    strength: 0,
    dexterity: 0,
    vitality: 410,
    intelligence: 0,
    mind: 409,
    criticalhit: 212,
    determination: 303,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/7/70/Augmented_Isnae_Phis_Icon.png'
    },
    {
      id: -1,
    name: '=Monk=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1018,
    name: 'Mandervillous Fists',
    slot: 'Weapon',
    damage: 132,
    strength: 416,
    dexterity: 0,
    vitality: 458,
    intelligence: 0,
    mind: 0,
    criticalhit: 306,
    determination: 306,
    directhit: 72,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/b/b1/Mandervillous_Fists_Icon.png'
    },
    {
      id: 1017,
    name: 'Augmented Dragons Beard Fists',
    slot: 'Weapon',
    damage: 131,
    strength: 409,
    dexterity: 0,
    vitality: 456,
    intelligence: 0,
    mind: 0,
    criticalhit: 212,
    determination: 303,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/3/35/Augmented_Dragon%27s_Beard_Fists_Icon.png'
    },
    {
      id: -1,
    name: '=Dragoon=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1018,
    name: 'Mandervillous Trident',
    slot: 'Weapon',
    damage: 132,
    strength: 416,
    dexterity: 0,
    vitality: 458,
    intelligence: 0,
    mind: 0,
    criticalhit: 306,
    determination: 306,
    directhit: 72,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/4/4c/Mandervillous_Trident_Icon.png'
    },
    {
      id: 1019,
    name: 'Augmented Nights Wolf',
    slot: 'Weapon',
    damage: 131,
    strength: 409,
    dexterity: 0,
    vitality: 456,
    intelligence: 0,
    mind: 0,
    criticalhit: 212,
    determination: 303,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/b/b2/Augmented_Night%27s_Wolf_Icon.png'
    },
    {
      id: -1,
    name: '=Ninja=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1014,
    name: 'Mandervillous Knives',
    slot: 'Weapon',
    damage: 132,
    strength: 0,
    dexterity: 416,
    vitality: 458,
    intelligence: 0,
    mind: 0,
    criticalhit: 306,
    determination: 306,
    directhit: 72,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/3/3b/Mandervillous_Knives_Icon.png'
    },
    {
      id: 1019,
    name: 'Augmented Shinobi Knives',
    slot: 'Weapon',
    damage: 131,
    strength: 0,
    dexterity: 409,
    vitality: 456,
    intelligence: 0,
    mind: 0,
    criticalhit: 212,
    determination: 303,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/3/39/Augmented_Shinobi_Knives_Icon.png'
    },
    {
      id: -1,
    name: '=Samurai=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1018,
    name: 'Mandervillous Samurai Blade',
    slot: 'Weapon',
    damage: 132,
    strength: 416,
    dexterity: 0,
    vitality: 458,
    intelligence: 0,
    mind: 0,
    criticalhit: 306,
    determination: 306,
    directhit: 72,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/1/14/Mandervillous_Samurai_Blade_Icon.png'
    },
    {
      id: 1022,
    name: 'Augmented Higan Shigan',
    slot: 'Weapon',
    damage: 131,
    strength: 409,
    dexterity: 0,
    vitality: 456,
    intelligence: 0,
    mind: 0,
    criticalhit: 212,
    determination: 303,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/7/7d/Augmented_Higan_Shigan_Icon.png'
    },
    {
      id: -1,
    name: '=Reaper=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1023,
    name: 'Mandervillous Zaghnal',
    slot: 'Weapon',
    damage: 132,
    strength: 416,
    dexterity: 0,
    vitality: 458,
    intelligence: 0,
    mind: 0,
    criticalhit: 306,
    determination: 306,
    directhit: 72,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/4/4e/Mandervillous_Zaghnal_Icon.png'
    },
    {
      id: 1025,
    name: 'Augmented Avatars Scythe',
    slot: 'Weapon',
    damage: 131,
    strength: 409,
    dexterity: 0,
    vitality: 456,
    intelligence: 0,
    mind: 0,
    criticalhit: 212,
    determination: 303,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/7/71/Augmented_Avatar%27s_Scythe_Icon.png'
    },
    {
      id: -1,
    name: '=Bard=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1026,
    name: 'Mandervillous Compound Bow',
    slot: 'Weapon',
    damage: 132,
    strength: 0,
    dexterity: 416,
    vitality: 458,
    intelligence: 0,
    mind: 0,
    criticalhit: 306,
    determination: 306,
    directhit: 72,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/a/a9/Mandervillous_Compound_Bow_Icon.png'
    },
    {
      id: 1027,
    name: 'Augmented Bluebirds Nest',
    slot: 'Weapon',
    damage: 131,
    strength: 0,
    dexterity: 409,
    vitality: 456,
    intelligence: 0,
    mind: 0,
    criticalhit: 212,
    determination: 303,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/8/8f/Augmented_Bluebird%27s_Nest_Icon.png'
    },
    {
      id: -1,
    name: '=Machinist=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1026,
    name: 'Mandervillous Revolver',
    slot: 'Weapon',
    damage: 132,
    strength: 0,
    dexterity: 416,
    vitality: 458,
    intelligence: 0,
    mind: 0,
    criticalhit: 306,
    determination: 306,
    directhit: 72,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/5/50/Mandervillous_Revolver_Icon.png'
    },
    {
      id: 1029,
    name: 'Augmented Vitória do Povo',
    slot: 'Weapon',
    damage: 131,
    strength: 0,
    dexterity: 409,
    vitality: 456,
    intelligence: 0,
    mind: 0,
    criticalhit: 212,
    determination: 303,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/0/0a/Augmented_Vit%C3%B3ria_do_Povo_Icon.png'
    },
    {
      id: -1,
    name: '=Dancer=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1030,
    name: 'Mandervillous Chakrams',
    slot: 'Weapon',
    damage: 132,
    strength: 0,
    dexterity: 416,
    vitality: 458,
    intelligence: 0,
    mind: 0,
    criticalhit: 306,
    determination: 72,
    directhit: 306,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/2/25/Mandervillous_Chakrams_Icon.png'
    },
    {
      id: 1031,
    name: 'Augmented Twin Moons',
    slot: 'Weapon',
    damage: 131,
    strength: 0,
    dexterity: 409,
    vitality: 456,
    intelligence: 0,
    mind: 0,
    criticalhit: 212,
    determination: 303,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/5/54/Augmented_Twin_Moons_Icon.png'
    },
    {
      id: -1,
    name: '=Black Mage=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1034,
    name: 'Mandervillous Rod',
    slot: 'Weapon',
    damage: 132,
    strength: 0,
    dexterity: 0,
    vitality: 412,
    intelligence: 416,
    mind: 0,
    criticalhit: 306,
    determination: 306,
    directhit: 72,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/8/89/Mandervillous_Rod_Icon.png'
    },
    {
      id: 1033,
    name: 'Augmented Ignis Malus',
    slot: 'Weapon',
    damage: 131,
    strength: 0,
    dexterity: 0,
    vitality: 410,
    intelligence: 409,
    mind: 0,
    criticalhit: 212,
    determination: 303,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/6/66/Augmented_Ignis_Malus_Icon.png'
    },
    {
      id: -1,
    name: '=Summoner=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1034,
    name: 'Mandervillous Index',
    slot: 'Weapon',
    damage: 132,
    strength: 0,
    dexterity: 0,
    vitality: 412,
    intelligence: 416,
    mind: 0,
    criticalhit: 306,
    determination: 306,
    directhit: 72,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/1/1f/Mandervillous_Index_Icon.png'
    },
    {
      id: 1035,
    name: 'Augmented Encounter in Lilies',
    slot: 'Weapon',
    damage: 131,
    strength: 0,
    dexterity: 0,
    vitality: 410,
    intelligence: 409,
    mind: 0,
    criticalhit: 212,
    determination: 303,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/2/2a/Augmented_Encounter_in_Lilies_Icon.png'
    },
    {
      id: -1,
    name: '=Red Mage=',
    slot: '',
    damage: 0,
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
    {
      id: 1034,
    name: 'Mandervillous Rapier',
    slot: 'Weapon',
    damage: 132,
    strength: 0,
    dexterity: 0,
    vitality: 412,
    intelligence: 416,
    mind: 0,
    criticalhit: 306,
    determination: 306,
    directhit: 72,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/c/cc/Mandervillous_Rapier_Icon.png'
    },
    {
      id: 1037,
    name: 'Augmented Lamplight Crook',
    slot: 'Weapon',
    damage: 131,
    strength: 0,
    dexterity: 0,
    vitality: 410,
    intelligence: 409,
    mind: 0,
    criticalhit: 212,
    determination: 303,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/e/e1/Augmented_Lamplight_Crook_Icon.png'
    },
  ]

  getItems() : Items[] {
    return this.itemsList
  }
}