import { Injectable } from '@angular/core';
import { Legs } from './legs';

@Injectable({
  providedIn: 'root'
})
export class LegsService {

  legsList: Legs[] = [
    { 
      id: 5000,
      name: '',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
      { 
      id: -1,
      name: '=Fending=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 5001,
      name: 'Ascension Hose of Fending',
      slot: 'Legs',
      strength: 394,
      dexterity: 0,
      vitality: 440,
      intelligence: 0,
      mind: 0,
      criticalhit: 204,
      determination: 292,
      directhit: 0,
      defense: 1196,
      magicdefense: 1196,
      tenacity: 129,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/b/ba/Ascension_Hose_of_Fending_Icon.png'
      },
      { 
      id: 5002,
      name: 'Augmented Credendum Breeches of Fending',
      slot: 'Legs',
      strength: 394,
      dexterity: 0,
      vitality: 440,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 292,
      directhit: 0,
      defense: 1196,
      magicdefense: 1196,
      tenacity: 204,
      piety: 0,
      skillspeed: 184,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/1/14/Augmented_Credendum_Breeches_of_Fending_Icon.png'
      },
      { 
      id: 5015,
      name: 'Augmented Diadochos Poleyns of Fending',
      slot: 'Legs',
      strength: 374,
      dexterity: 0,
      vitality: 413,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 286,
      directhit: 0,
      defense: 1196,
      magicdefense: 1196,
      tenacity: 200,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/0/0a/Augmented_Diadochos_Poleyns_of_Fending_Icon.png'
      },
      { 
      id: -1,
      name: '=Healing=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 5003,
      name: 'Ascension Longkilt of Healing',
      slot: 'Legs',
      strength: 0,
      dexterity: 0,
      vitality: 396,
      intelligence: 0,
      mind: 394,
      criticalhit: 0,
      determination: 204,
      directhit: 0,
      defense: 478,
      magicdefense: 837,
      tenacity: 0,
      piety: 292,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/3/34/Ascension_Longkilt_of_Healing_Icon.png'
      },
      { 
      id: 5004,
      name: 'Augmented Credendum Hose of Healing',
      slot: 'Legs',
      strength: 0,
      dexterity: 0,
      vitality: 396,
      intelligence: 0,
      mind: 394,
      criticalhit: 292,
      determination: 204,
      directhit: 0,
      defense: 478,
      magicdefense: 837,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/5/5d/Augmented_Credendum_Hose_of_Healing_Icon.png'
      },
      { 
      id: 5016,
      name: 'Augmented Diadochos Bottoms of Healing',
      slot: 'Legs',
      strength: 0,
      dexterity: 0,
      vitality: 372,
      intelligence: 0,
      mind: 374,
      criticalhit: 286,
      determination: 200,
      directhit: 0,
      defense: 468,
      magicdefense: 820,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/e/ed/Augmented_Diadochos_Bottoms_of_Healing_Icon.png'
      },
      { 
        id: -1,
        name: '=Striking=',
        slot: '',
        strength: 0,
        dexterity: 0,
        vitality: 0,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 0,
        directhit: 0,
        defense: 0,
        magicdefense: 0,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: ''
        },
      { 
        id: 5005,
        name: 'Ascension Hose of Striking',
        slot: 'Legs',
        strength: 394,
        dexterity: 0,
        vitality: 440,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 292,
        directhit: 204,
        defense: 658,
        magicdefense: 658,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/1/11/Ascension_Hose_of_Striking_Icon.png'
        },
        { 
        id: 5006,
        name: 'Augmented Credendum Trousers of Striking',
        slot: 'Legs',
        strength: 394,
        dexterity: 0,
        vitality: 440,
        intelligence: 0,
        mind: 0,
        criticalhit: 292,
        determination: 0,
        directhit: 204,
        defense: 658,
        magicdefense: 658,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/a/ad/Augmented_Credendum_Trousers_of_Striking_Icon.png'
      },
      
      { 
        id: 5017,
        name: 'Augmented Diadochos Bottoms of Striking',
        slot: 'Legs',
        strength: 374,
        dexterity: 0,
        vitality: 413,
        intelligence: 0,
        mind: 0,
        criticalhit: 286,
        determination: 200,
        directhit: 0,
        defense: 644,
        magicdefense: 644,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/8/8e/Augmented_Diadochos_Bottoms_of_Striking_Icon.png'
      },
      { 
        id: -1,
        name: '=Maiming=',
        slot: '',
        strength: 0,
        dexterity: 0,
        vitality: 0,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 0,
        directhit: 0,
        defense: 0,
        magicdefense: 0,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: ''
        },
      { 
        id: 5007,
        name: 'Ascension Hose of Maiming',
        slot: 'Legs',
        strength: 394,
        dexterity: 0,
        vitality: 440,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 292,
        directhit: 204,
        defense: 837,
        magicdefense: 658,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/d/dc/Ascension_Hose_of_Maiming_Icon.png'
        },
        { 
        id: 5008,
        name: 'Augmented Credendum Breeches of Maiming',
        slot: 'Legs',
        strength: 394,
        dexterity: 0,
        vitality: 440,
        intelligence: 0,
        mind: 0,
        criticalhit: 292,
        determination: 204,
        directhit: 0,
        defense: 837,
        magicdefense: 658,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/8/8e/Augmented_Credendum_Breeches_of_Maiming_Icon.png'
      },
      { 
      id: 5018,
      name: 'Augmented Diadochos Poleyns of Maiming',
      slot: 'Legs',
      strength: 374,
      dexterity: 0,
      vitality: 413,
      intelligence: 0,
      mind: 0,
      criticalhit: 200,
      determination: 0,
      directhit: 286,
      defense: 820,
      magicdefense: 644,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/e/e5/Augmented_Diadochos_Poleyns_of_Maiming_Icon.png'
    },
      { 
    id: -1,
    name: '=Scouting=',
    slot: '',
    strength: 0,
    dexterity: 0,
    vitality: 0,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 0,
    directhit: 0,
    defense: 0,
    magicdefense: 0,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: ''
    },
  { 
    id: 5009,
    name: 'Ascension Hose of Scouting',
    slot: 'Hands',
    strength: 0,
    dexterity: 394,
    vitality: 440,
    intelligence: 0,
    mind: 0,
    criticalhit: 0,
    determination: 204,
    directhit: 292,
    defense: 658,
    magicdefense: 658,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/4/45/Ascension_Hose_of_Scouting_Icon.png'
  },      
  { 
    id: 5010,
    name: 'Augmented Credendum Trousers of Scouting',
    slot: 'Legs',
    strength: 0,
    dexterity: 394,
    vitality: 440,
    intelligence: 0,
    mind: 0,
    criticalhit: 204,
    determination: 0,
    directhit: 292,
    defense: 658,
    magicdefense: 658,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/a/af/Augmented_Credendum_Trousers_of_Scouting_Icon.png'
    },      
  { 
    id: 5019,
    name: 'Augmented Diadochos Bottoms of Scouting',
    slot: 'Legs',
    strength: 0,
    dexterity: 374,
    vitality: 413,
    intelligence: 0,
    mind: 0,
    criticalhit: 200,
    determination: 0,
    directhit: 286,
    defense: 644,
    magicdefense: 644,
    tenacity: 0,
    piety: 0,
    skillspeed: 0,
    spellspeed: 0,
    photo: 'https://ffxiv.gamerescape.com/w/images/0/0f/Augmented_Diadochos_Bottoms_of_Scouting_Icon.png'
    },
        { 
      id: -1,
      name: '=Aiming=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 5011,
      name: 'Ascension Hose of Aiming',
      slot: 'Legs',
      strength: 0,
      dexterity: 394,
      vitality: 440,
      intelligence: 0,
      mind: 0,
      criticalhit: 204,
      determination: 292,
      directhit: 0,
      defense: 658,
      magicdefense: 658,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/8/86/Ascension_Hose_of_Aiming_Icon.png'
    },      
    { 
      id: 5012,
      name: 'Augmented Credendum Hose of Aiming',
      slot: 'Legs',
      strength: 0,
      dexterity: 394,
      vitality: 440,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 204,
      directhit: 292,
      defense: 658,
      magicdefense: 658,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/1/16/Augmented_Credendum_Hose_of_Aiming_Icon.png'
      },      
    { 
      id: 5020,
      name: 'Augmented Diadochos Poleyns of Aiming',
      slot: 'Legs',
      strength: 0,
      dexterity: 374,
      vitality: 413,
      intelligence: 0,
      mind: 0,
      criticalhit: 286,
      determination: 0,
      directhit: 200,
      defense: 644,
      magicdefense: 644,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/6/61/Augmented_Diadochos_Poleyns_of_Aiming_Icon.png'
      },
      { 
      id: -1,
      name: '=Casting=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 5013,
      name: 'Ascension Longkilt of Casting',
      slot: 'Legs',
      strength: 0,
      dexterity: 0,
      vitality: 396,
      intelligence: 394,
      mind: 0,
      criticalhit: 204,
      determination: 0,
      directhit: 292,
      defense: 478,
      magicdefense: 837,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/a/a1/Ascension_Longkilt_of_Casting_Icon.png'
      },      
      { 
      id: 5014,
      name: 'Augmented Credendum Hose of Casting',
      slot: 'Legs',
      strength: 0,
      dexterity: 0,
      vitality: 396,
      intelligence: 394,
      mind: 0,
      criticalhit: 0,
      determination: 292,
      directhit: 0,
      defense: 478,
      magicdefense: 837,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 204,
      photo: 'https://ffxiv.gamerescape.com/w/images/6/6e/Augmented_Credendum_Hose_of_Casting_Icon.png'
      },      
      { 
      id: 5021,
      name: 'Augmented Diadochos Bottoms of Casting',
      slot: 'Legs',
      strength: 0,
      dexterity: 0,
      vitality: 372,
      intelligence: 374,
      mind: 0,
      criticalhit: 200,
      determination: 0,
      directhit: 286,
      defense: 468,
      magicdefense: 820,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/9/93/Augmented_Diadochos_Bottoms_of_Casting_Icon.png'
      },
  ]

    getLegs() : Legs[] {
      return this.legsList
    }
}
