import { Injectable } from '@angular/core';
import { Necklaces } from './necklaces';

@Injectable({
  providedIn: 'root'
})
export class NecklacesService {

  necklacesList: Necklaces[] = [
    { 
      id: -1,
      name: '',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
      { 
      id: -1,
      name: '=Fending=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 8001,
      name: 'Ascension Necklace of Fending',
      slot: 'Necklace',
      strength: 196,
      dexterity: 0,
      vitality: 218,
      intelligence: 0,
      mind: 0,
      criticalhit: 145,
      determination: 102,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/0/0c/Ascension_Necklace_of_Fending_Icon.png'
      },
      { 
      id: 8002,
      name: 'Augmented Credendum Necklace of Fending',
      slot: 'Necklace',
      strength: 196,
      dexterity: 0,
      vitality: 196,
      intelligence: 0,
      mind: 0,
      criticalhit: 145,
      determination: 0,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 102,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/d/db/Augmented_Credendum_Necklace_of_Fending_Icon.png'
      },
      { 
      id: -1,
      name: '=Healing=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 8003,
      name: 'Ascension Necklace of Healing',
      slot: 'Necklace',
      strength: 0,
      dexterity: 0,
      vitality: 196,
      intelligence: 0,
      mind: 196,
      criticalhit: 0,
      determination: 145,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 102,
      photo: 'https://ffxiv.gamerescape.com/w/images/0/0c/Ascension_Necklace_of_Fending_Icon.png'      },
      { 
      id: 8004,
      name: 'Augmented Credendum Necklace of Healing',
      slot: 'Necklace',
      strength: 0,
      dexterity: 0,
      vitality: 196,
      intelligence: 0,
      mind: 196,
      criticalhit: 145,
      determination: 0,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 102,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/d/db/Augmented_Credendum_Necklace_of_Fending_Icon.png'
      },
      { 
        id: -1,
        name: '=Maiming, Striking=',
        slot: '',
        strength: 0,
        dexterity: 0,
        vitality: 0,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 0,
        directhit: 0,
        defense: 0,
        magicdefense: 0,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: ''
        },
      { 
        id: 8005,
        name: 'Ascension Necklace of Slaying',
        slot: 'Necklace',
        strength: 196,
        dexterity: 0,
        vitality: 218,
        intelligence: 0,
        mind: 0,
        criticalhit: 145,
        determination: 0,
        directhit: 102,
        defense: 1,
        magicdefense: 1,
        tenacity: 0,
        piety: 0,
        skillspeed: 145,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/0/0c/Ascension_Necklace_of_Fending_Icon.png'        },
        { 
        id: 8006,
        name: 'Augmented Credendum Necklace of Slaying',
        slot: 'Necklace',
        strength: 196,
        dexterity: 0,
        vitality: 218,
        intelligence: 0,
        mind: 0,
        criticalhit: 145,
        determination: 0,
        directhit: 102,
        defense: 1,
        magicdefense: 1,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/d/db/Augmented_Credendum_Necklace_of_Fending_Icon.png'
      },
        { 
      id: -1,
      name: '=Aiming, Scouting=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 8007,
      name: 'Ascension Necklace of Aiming',
      slot: 'Necklace',
      strength: 0,
      dexterity: 196,
      vitality: 218,
      intelligence: 0,
      mind: 0,
      criticalhit: 145,
      determination: 102,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/0/0c/Ascension_Necklace_of_Fending_Icon.png'      },
      { 
      id: 8008,
      name: 'Augmented Credendum Necklace of Aiming',
      slot: 'Necklace',
      strength: 0,
      dexterity: 196,
      vitality: 218,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 102,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 145,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/d/db/Augmented_Credendum_Necklace_of_Fending_Icon.png'
      },
      { 
      id: -1,
      name: '=Casting=',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
    { 
      id: 8009,
      name: 'Ascension Necklace of Casting',
      slot: 'Necklace',
      strength: 0,
      dexterity: 0,
      vitality: 196,
      intelligence: 196,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 145,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 102,
      photo: 'https://ffxiv.gamerescape.com/w/images/0/0c/Ascension_Necklace_of_Fending_Icon.png'      },
      { 
      id: 8010,
      name: 'Augmented Credendum Necklace of Fending',
      slot: 'Necklace',
      strength: 0,
      dexterity: 0,
      vitality: 196,
      intelligence: 196,
      mind: 0,
      criticalhit: 102,
      determination: 145,
      directhit: 0,
      defense: 1,
      magicdefense: 1,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: 'https://ffxiv.gamerescape.com/w/images/d/db/Augmented_Credendum_Necklace_of_Fending_Icon.png'
      },
  ]

  getNecklaces() : Necklaces[] {
    return this.necklacesList
  }
  
}
