import { Injectable } from '@angular/core';
import { Rings } from './rings';

@Injectable({
  providedIn: 'root'
})
export class RingsService {

  ringsList: Rings[] = [
    { 
      id: 10000,
      name: '',
      slot: '',
      strength: 0,
      dexterity: 0,
      vitality: 0,
      intelligence: 0,
      mind: 0,
      criticalhit: 0,
      determination: 0,
      directhit: 0,
      defense: 0,
      magicdefense: 0,
      tenacity: 0,
      piety: 0,
      skillspeed: 0,
      spellspeed: 0,
      photo: ''
      },
      { 
        id: -1,
        name: '=Fending=',
        slot: '',
        strength: 0,
        dexterity: 0,
        vitality: 0,
        intelligence: 0,
        mind: 0,
        criticalhit: 0,
        determination: 0,
        directhit: 0,
        defense: 0,
        magicdefense: 0,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: ''
        },
      { 
        id: 10001,
        name: 'Ascension Ring of Fending',
        slot: 'Ring',
        strength: 196,
        dexterity: 0,
        vitality: 218,
        intelligence: 0,
        mind: 0,
        criticalhit: 145,
        determination: 0,
        directhit: 0,
        defense: 1,
        magicdefense: 1,
        tenacity: 0,
        piety: 0,
        skillspeed: 102,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/6/65/Ascension_Ring_of_Fending_Icon.png'
        },
    { 
        id: 10002,
        name: 'Augmented Credendum Ring of Fending',
        slot: 'Ring',
        strength: 196,
        dexterity: 0,
        vitality: 218,
        intelligence: 0,
        mind: 0,
        criticalhit: 102,
        determination: 145,
        directhit: 0,
        defense: 1,
        magicdefense: 1,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/1/18/Augmented_Credendum_Ring_of_Fending_Icon.png'
        },
        { 
        id: 10003,
        name: 'Augmented Diadochos Ring of Fending',
        slot: 'Ring',
        strength: 186,
        dexterity: 0,
        vitality: 205,
        intelligence: 0,
        mind: 0,
        criticalhit: 99,
        determination: 142,
        directhit: 0,
        defense: 1,
        magicdefense: 1,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/6/6b/Augmented_Diadochos_Ring_of_Fending_Icon.png'
        },
        { 
        id: 10004,
        name: 'Credendum Ring of Fending',
        slot: 'Ring',
        strength: 186,
        dexterity: 0,
        vitality: 205,
        intelligence: 0,
        mind: 0,
        criticalhit: 99,
        determination: 142,
        directhit: 0,
        defense: 1,
        magicdefense: 1,
        tenacity: 0,
        piety: 0,
        skillspeed: 0,
        spellspeed: 0,
        photo: 'https://ffxiv.gamerescape.com/w/images/f/f1/Credendum_Ring_of_Fending_Icon.png'
        },

        { 
          id: -1,
          name: '=Healing=',
          slot: '',
          strength: 0,
          dexterity: 0,
          vitality: 0,
          intelligence: 0,
          mind: 0,
          criticalhit: 0,
          determination: 0,
          directhit: 0,
          defense: 0,
          magicdefense: 0,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 0,
          photo: ''
          },
          { 
          id: 10005,
          name: 'Ascension Ring of Healing',
          slot: 'Ring',
          strength: 0,
          dexterity: 0,
          vitality: 196,
          intelligence: 0,
          mind: 196,
          criticalhit: 102,
          determination: 0,
          directhit: 0,
          defense: 1,
          magicdefense: 1,
          tenacity: 0,
          piety: 145,
          skillspeed: 0,
          spellspeed: 0,
          photo: 'https://ffxiv.gamerescape.com/w/images/c/c2/Ascension_Ring_of_Healing_Icon.png'
          },
          { 
          id: 10006,
          name: 'Augmented Credendum Ring of Healing',
          slot: 'Ring',
          strength: 0,
          dexterity: 0,
          vitality: 196,
          intelligence: 0,
          mind: 196,
          criticalhit: 145,
          determination: 102,
          directhit: 0,
          defense: 1,
          magicdefense: 1,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 0,
          photo: 'https://ffxiv.gamerescape.com/w/images/f/f9/Augmented_Credendum_Ring_of_Healing_Icon.png'
          },
          { 
          id: 10007,
          name: 'Augmented Diadochos Ring of Healing',
          slot: 'Ring',
          strength: 0,
          dexterity: 0,
          vitality: 185,
          intelligence: 0,
          mind: 186,
          criticalhit: 99,
          determination: 142,
          directhit: 0,
          defense: 1,
          magicdefense: 1,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 0,
          photo: 'https://ffxiv.gamerescape.com/w/images/e/ef/Augmented_Diadochos_Ring_of_Healing_Icon.png'
          },
          { 
          id: 10008,
          name: 'Credendum Ring of Healing',
          slot: 'Ring',
          strength: 0,
          dexterity: 0,
          vitality: 185,
          intelligence: 0,
          mind: 186,
          criticalhit: 142,
          determination: 99,
          directhit: 0,
          defense: 1,
          magicdefense: 1,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 0,
          photo: 'https://ffxiv.gamerescape.com/w/images/6/66/Credendum_Ring_of_Healing_Icon.png'
          },
          { 
          id: -1,
          name: '=Maiming, Striking=',
          slot: '',
          strength: 0,
          dexterity: 0,
          vitality: 0,
          intelligence: 0,
          mind: 0,
          criticalhit: 0,
          determination: 0,
          directhit: 0,
          defense: 0,
          magicdefense: 0,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 0,
          photo: ''
          },
          { 
          id: 10009,
          name: 'Ascension Ring of Slaying',
          slot: 'Ring',
          strength: 196,
          dexterity: 0,
          vitality: 218,
          intelligence: 0,
          mind: 0,
          criticalhit: 102,
          determination: 145,
          directhit: 0,
          defense: 1,
          magicdefense: 1,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 0,
          photo: 'https://ffxiv.gamerescape.com/w/images/a/a0/Ascension_Ring_of_Slaying_Icon.png'
          },
          { 
          id: 10010,
          name: 'Augmented Credendum Ring of Slaying',
          slot: 'Ring',
          strength: 196,
          dexterity: 0,
          vitality: 218,
          intelligence: 0,
          mind: 0,
          criticalhit: 145,
          determination: 0,
          directhit: 102,
          defense: 1,
          magicdefense: 1,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 0,
          photo: 'https://ffxiv.gamerescape.com/w/images/9/93/Augmented_Credendum_Ring_of_Slaying_Icon.png'
          },
          { 
          id: 10011,
          name: 'Augmented Diadochos Ring of Slaying',
          slot: 'Ring',
          strength: 186,
          dexterity: 0,
          vitality: 205,
          intelligence: 0,
          mind: 0,
          criticalhit: 142,
          determination: 0,
          directhit: 99,
          defense: 1,
          magicdefense: 1,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 0,
          photo: 'https://ffxiv.gamerescape.com/w/images/4/40/Augmented_Diadochos_Ring_of_Slaying_Icon.png'
          },
          { 
          id: 10012,
          name: 'Credendum Ring of Slaying',
          slot: 'Ring',
          strength: 186,
          dexterity: 0,
          vitality: 205,
          intelligence: 0,
          mind: 0,
          criticalhit: 142,
          determination: 0,
          directhit: 99,
          defense: 1,
          magicdefense: 1,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 0,
          photo: 'https://ffxiv.gamerescape.com/w/images/3/38/Credendum_Ring_of_Slaying_Icon.png'
          },
          { 
          id: -1,
          name: '=Aiming, Scouting=',
          slot: '',
          strength: 0,
          dexterity: 0,
          vitality: 0,
          intelligence: 0,
          mind: 0,
          criticalhit: 0,
          determination: 0,
          directhit: 0,
          defense: 0,
          magicdefense: 0,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 0,
          photo: ''
          },
          { 
          id: 10013,
          name: 'Ascension Ring of Aiming',
          slot: 'Ring',
          strength: 0,
          dexterity: 196,
          vitality: 218,
          intelligence: 0,
          mind: 0,
          criticalhit: 102,
          determination: 0,
          directhit: 145,
          defense: 1,
          magicdefense: 1,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 0,
          photo: 'https://ffxiv.gamerescape.com/w/images/a/a0/Ascension_Ring_of_Slaying_Icon.png'
          },
          { 
          id: 10014,
          name: 'Augmented Credendum Ring of Aiming',
          slot: 'Ring',
          strength: 0,
          dexterity: 196,
          vitality: 218,
          intelligence: 0,
          mind: 0,
          criticalhit: 145,
          determination: 102,
          directhit: 0,
          defense: 1,
          magicdefense: 1,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 0,
          photo: 'https://ffxiv.gamerescape.com/w/images/9/93/Augmented_Credendum_Ring_of_Slaying_Icon.png'
          },
          { 
            id: 10015,
            name: 'Augmented Diadochos Ring of Aiming',
            slot: 'Ring',
            strength: 0,
            dexterity: 186,
            vitality: 205,
            intelligence: 0,
            mind: 0,
            criticalhit:99,
            determination: 142,
            directhit: 0,
            defense: 1,
            magicdefense: 1,
            tenacity: 0,
            piety: 0,
            skillspeed: 0,
            spellspeed: 0,
            photo: 'https://ffxiv.gamerescape.com/w/images/1/10/Augmented_Diadochos_Ring_of_Aiming_Icon.png'
            },
          { 
            id: 10016,
            name: 'Credendum Ring of Aiming',
            slot: 'Ring',
            strength: 0,
            dexterity: 186,
            vitality: 205,
            intelligence: 0,
            mind: 0,
            criticalhit:142,
            determination: 99,
            directhit: 0,
            defense: 1,
            magicdefense: 1,
            tenacity: 0,
            piety: 0,
            skillspeed: 0,
            spellspeed: 0,
            photo: 'https://ffxiv.gamerescape.com/w/images/3/3a/Credendum_Ring_of_Aiming_Icon.png'
            },
          { 
          id: -1,
          name: '=Casting=',
          slot: '',
          strength: 0,
          dexterity: 0,
          vitality: 0,
          intelligence: 0,
          mind: 0,
          criticalhit: 0,
          determination: 0,
          directhit: 0,
          defense: 1,
          magicdefense: 1,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 0,
          photo: ''
          },
          { 
          id: 10017,
          name: 'Ascension Ring of Casting',
          slot: 'Ring',
          strength: 0,
          dexterity: 0,
          vitality: 196,
          intelligence: 196,
          mind: 0,
          criticalhit: 145,
          determination: 102,
          directhit: 0,
          defense: 1,
          magicdefense: 1,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 0,
          photo: 'https://ffxiv.gamerescape.com/w/images/a/a0/Ascension_Ring_of_Slaying_Icon.png'
          },
          { 
          id: 10018,
          name: 'Augmented Credendum Ring of Casting',
          slot: 'Ring',
          strength: 0,
          dexterity: 0,
          vitality: 196,
          intelligence: 196,
          mind: 0,
          criticalhit: 0,
          determination: 0,
          directhit: 145,
          defense: 1,
          magicdefense: 1,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 102,
          photo: 'https://ffxiv.gamerescape.com/w/images/9/93/Augmented_Credendum_Ring_of_Slaying_Icon.png'
          },
          { 
          id: 10019,
          name: 'Augmented Diadochos Ring of Casting',
          slot: 'Ring',
          strength: 0,
          dexterity: 0,
          vitality: 185,
          intelligence: 186,
          mind: 0,
          criticalhit: 142,
          determination: 0,
          directhit: 0,
          defense: 1,
          magicdefense: 1,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 99,
          photo: 'https://ffxiv.gamerescape.com/w/images/4/46/Augmented_Diadochos_Ring_of_Casting_Icon.png'
          },
          { 
          id: 10020,
          name: 'Credendum Ring of Casting',
          slot: 'Ring',
          strength: 0,
          dexterity: 0,
          vitality: 185,
          intelligence: 186,
          mind: 0,
          criticalhit: 0,
          determination: 0,
          directhit: 142,
          defense: 1,
          magicdefense: 1,
          tenacity: 0,
          piety: 0,
          skillspeed: 0,
          spellspeed: 99,
          photo: 'https://ffxiv.gamerescape.com/w/images/3/31/Credendum_Ring_of_Casting_Icon.png'
          },
  ]

  getRings() : Rings[] {
    return this.ringsList
  }
  
}
